### ISSUE TITLE
Add "Report Issue" button

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/playground#4]
https://github.com/Unibeautify/playground/blob/master/src/Container.tsx#L110-L117

**Comment by szeck87** [comment]
What should this do exactly?

**Comment by Glavin001** [comment]
I'm on the fence about this.

I want to have something like the `Report Issue` button from https://prettier.io/playground/
However, in our case we have multiple beautifiers. I was thinking if you have multiple beautifier's selected and click "Report Issue" then it would ask "Please select only 1 beautifier" and once you have only one selected then it would open on GitHub for the particular beautifier.

My goal is to guide there user to reporting errors to the right place. I do not want Unibeautify core to have a bunch of language or beautifier specific errors and become cluttered like Atom-Beautify has.
